=== cbang/SnoParator/src/xml/subset.xsd
<?xml version="1.0" encoding="UTF-8"?>
   <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
         <xs:element name="subset">
               <xs:complexType>
                     <xs:sequence>
                           <xs:element name="normForms">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="normForm" maxOccurs="unbounded">
                                                   <xs:complexType>
                                                         <xs:sequence>
                                                               <xs:element name="fcsId" type="xs:int" maxOccurs="1"></xs:element>
                                                               <xs:element name="relationshipGroups" maxOccurs="unbounded">
                                                                     <xs:complexType>
                                                                           <xs:sequence>
                                                                                 <xs:element name="relationshipGroup" maxOccurs="unbounded">
                                                                                       <xs:complexType>
                                                                                             <xs:sequence>
                                                                                                   <xs:element name="relationships">
                                                                                                         <xs:complexType>
                                                                                                               <xs:sequence>
                                                                                                                     <xs:element name="relationship" maxOccurs="unbounded">
                                                                                                                           <xs:complexType>
                                                                                                                                 <xs:sequence>
                                                                                                                                       <xs:element name="attribute" type="xs:int"></xs:element>
                                                                                                                                       <xs:element name="destId" type="xs:int"></xs:element>
                                                                                                                                 </xs:sequence>
                                                                                                                           </xs:complexType>
                                                                                                                     </xs:element>
                                                                                                               </xs:sequence>
                                                                                                         </xs:complexType>
                                                                                                   </xs:element>
                                                                                             </xs:sequence>
                                                                                             <xs:attribute name="explicit" type="xs:string"></xs:attribute>
                                                                                       </xs:complexType>
                                                                                 </xs:element>
                                                                           </xs:sequence>
                                                                     </xs:complexType>
                                                               </xs:element>
                                                         </xs:sequence>
                                                   </xs:complexType>
                                             </xs:element>
                                       </xs:sequence>
                                 </xs:complexType>
                           </xs:element>
                     </xs:sequence>
               </xs:complexType>
         </xs:element>
   </xs:schema>

=== cbang/SnoParator/src/xml/subAXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<subset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="subset.xsd">
    <normForms> 
        <normForm> 
            <fcsId>301273002</fcsId> <!--Abnormal breath sounds-->
            <relationshipGroups>
                <relationshipGroup explicit="false">
                    <relationships>
                        <relationship>
                            <attribute>363698007</attribute> <!--finding site-->
                            <destId>82094008</destId> <!--lower respiratory tract structure -->
                        </relationship>
                        <relationship>
                            <attribute>363714003</attribute> <!--interprets-->
                            <destId>52653008</destId> <!--respiratory sounds-->
                        </relationship>
                        <relationship>
                            <attribute>418775008</attribute> <!--method-->
                            <destId>129436005</destId> <!--auscultation-->
                        </relationship>
                    </relationships>
                </relationshipGroup>
            </relationshipGroups>
        </normForm>  
        <normForm>
            <fcsId>194828000</fcsId> <!--angina pectoris-->
            <relationshipGroups>
                <relationshipGroup explicit="false">
                    <relationships>
                        <relationship>
                            <attribute>363705008</attribute> <!--has definitional manifestation-->
                            <destId>22253000</destId> <!--pain-->
                        </relationship>
                    </relationships>
                </relationshipGroup>
                <relationshipGroup explicit="true">
                    <relationships>
                        <relationship>
                            <attribute>116676008</attribute> <!--associated morphology-->
                            <destId>449735000</destId> <!--structural change due to ischemia -->
                        </relationship>
                        <relationship>
                            <attribute>363698007</attribute> <!--finding site-->
                            <destId>80891009</destId> <!--heart structure-->
                        </relationship>
                    </relationships>
                </relationshipGroup>
            </relationshipGroups>
        </normForm>
        <normForm>
            <fcsId>62315008</fcsId> <!--Diarrhea-->
            <relationshipGroups>
                <relationshipGroup explicit="false">
                    <relationships>
                        <relationship>
                            <attribute>363698007</attribute> <!--finding site-->
                            <destId>122865005</destId> <!--gastrointestinal tract structure-->
                        </relationship>
                    </relationships>
                </relationshipGroup>
                <relationshipGroup explicit="true">
                    <relationships>
                        <relationship>
                            <attribute>363713009</attribute> <!--has interpretation-->
                            <destId>18307000</destId> <!--altered-->
                        </relationship>
                        <relationship>
                            <attribute>363714003</attribute> <!--interprets-->
                            <destId>39211005</destId> <!--bowel action-->
                        </relationship>
                    </relationships>
                </relationshipGroup>
            </relationshipGroups>
        </normForm> 
    </normForms>
</subset>
